### ISSUE TITLE
Automate Number of levels and downsampling factor

### ISSUE THREAD

**Issue by lacan** [BIOP/ijp-kheops#1]
Hello fellow coders. 

Perhaps we can simplify this and have a "basic" mode which calculates the downsampling and number of levels automatically.

Perhaps like this.
1. Set downsampling to 2 unless there are more than 6 pyramid levels
2. Compute pyramid levels as follows

(Pseudocode)
```java
smallest = MIN( width, height )
downsample = 2
smallest_pyramid = 512
max_levels = 6

nlevels = Math.ceiling( log( smallest  - log( smallest_pyramid ) / log ( downsample ) )

while( nlevels > max_levels ) {
    downsample *=2 
    nlevels = Math.ceiling( log( smallest  - log( smallest_pyramid ) / log ( downsample ) )
}
```

**Comment by romainGuiet** [comment]
Issue was solved by adding KheopsSimpleCommand.java  https://github.com/BIOP/ijp-kheops/commit/3474c6923c024ef4a4c0f9bbfb538443ad77aaaa

**Comment by lacan** [comment]
Woo++
