### ISSUE TITLE
VSI Files: Overviews Cause Errors

### ISSUE THREAD

**Issue by lacan** [BIOP/ijp-kheops#3]
Overviews are very small images and require to set a very small tile size. 

Is there a way to exclude these files from the VSI conversion?

To replicate: Try to convert a VSI file using a large tile size

To correct: Perhaps manage to export smaller images without tiles, but as regular tiffs?

**Comment by romainGuiet** [comment]
Open a[ thread on image.sc](https://forum.image.sc/t/bfconvert-error-with-vsi-file/39534)

**Comment by NicoKiaru** [comment]
Normally fixed now.
