### ISSUE TITLE
Allow for selecting compression algorithm

### ISSUE THREAD

**Issue by lacan** [BIOP/ijp-kheops#4]
Personal reminder
Saving to ome.tiff pyramids allows for JPEG-2000 and JPEG-2000 Lossy compression to be done, reducing the file size by a factor 10. It would be interesting to implement this

**Comment by imagejan** [comment]
I'd be interested in having compression options for OME-TIFF conversion as well.

What about [LZW compression](https://docs.openmicroscopy.org/bio-formats/6.5.0/users/comlinetools/conversion.html#cmdoption-bfconvert-compression)? Does your plugin support this already?

**Comment by romainGuiet** [comment]
just made a push of a new command [KheopsAdv](https://github.com/BIOP/ijp-kheops/blob/master/src/main/java/ch/epfl/biop/ij2command/KheopsAdvCommand.java)
