### ISSUE TITLE
Consider continuous integration and deployment to maven.scijava.org

### ISSUE THREAD

**Issue by imagejan** [BIOP/ijp-kheops#5]
This would make it easier for others to use/depend on `ijp-kheops`.

Please let me know and I can travisify the repo and file a PR.

**Comment by NicoKiaru** [comment]
This would be awesome - but we don't know if the repo in a good shape now - maybe we should resolve some issues (documentation / license) before ? Or it doesn't matter ?

**Comment by imagejan** [comment]
The license issue (#6) should maybe better be solved to clarify the situation, yes.

**Comment by romainGuiet** [comment]
#6 is now closed ( 🤞 )

**Comment by imagejan** [comment]
Closed by #7.
