### ISSUE TITLE
Sanitize license information

### ISSUE THREAD

**Issue by imagejan** [BIOP/ijp-kheops#6]
This repo doesn't seem to use a standard `LICENSE` file, so GitHub unfortunately doesn't detect the license of this component.

In `license.txt`, it says:

https://github.com/BIOP/ijp-kheops/blob/ce3ab41d3b2f07c6caf98d3b85a83c02869b2b8e/license.txt#L9

while in `pom.xml`, you have:

https://github.com/BIOP/ijp-kheops/blob/ce3ab41d3b2f07c6caf98d3b85a83c02869b2b8e/pom.xml#L27-L31

and

https://github.com/BIOP/ijp-kheops/blob/ce3ab41d3b2f07c6caf98d3b85a83c02869b2b8e/pom.xml#L124-L125

---

I guess the *intended* license was BSD-3-Clause?

**Comment by romainGuiet** [comment]
"I guess the intended license was BSD-3-Clause?" indeed it was the initial thought.
Thank you for noticing it!

Do you know if it id compatible with [bioformats licensing](https://www.openmicroscopy.org/licensing/)

Cheers

**Comment by imagejan** [comment]
Good point. I think since Bio-Formats is licensed under a very strong copyleft (GPLv2), and `ijp-kheops` tightly integrates with the Bio-Formats API, you might have to license under GPLv2 as well...

**Comment by romainGuiet** [comment]
Hi Jan, 
I found this  [thread](https://opensource.stackexchange.com/questions/7180/can-i-combine-gplv2-and-bsd-3-clause-code-and-keep-the-bsd-permissions) about a similar question and following your and their recommendations we just copy and paste the  [license from ome](https://github.com/ome/bioformats/blob/develop/components/formats-gpl/pom.xml)
Thank you again
Cheers,
R

**Comment by romainGuiet** [comment]
Just made a new [push with the new license](https://github.com/BIOP/ijp-kheops/commit/9a12df00545a7c4040f68531dfff06a2a110ec7e #)
