### ISSUE TITLE
Export a currently opened image to pyramidal ome.tiff

### ISSUE THREAD

**Issue by binli123** [BIOP/ijp-kheops#9]
Hi, thanks much for making this useful tool. I was wondering if you could add a feature that allows the user to directly save an opened image into pyramidal ome.tif?

**Comment by NicoKiaru** [comment]
Hi @binli123, 

It's not really straightforward to do this in the way kheops is written. And it's not on the current plans to add such a feature. Of course one workaround is to save your data and then convert it, but there's an extra step I admit.

**Comment by NicoKiaru** [comment]
It should be done now. However there are some limitations : no tiling, and RGB images are not yet supported

see https://github.com/BIOP/ijp-kheops/commit/3054a3717795149d5a688715f1dafdf25c187b10
